# Get information from the FlashBlade
---
- name: Get information from the test FlashBlade
  hosts: localhost
  collections: 
    - purestorage.flashblade
  # Get API token with "pureadmin list --api-token --expose" on FlashBlade
  vars:
    fb_url: "poc-fb-mgmt"
    fb_api_token: "T-194591fd-af50-457a-b76b-123456789012"
    fb_data: "poc-fb-data-01"
    fb_fs_name: "vertica"
    fb_fs_size: "16T"
    fb_s3_acct: "vertica"
    fb_s3_user: "dbadmin"
    fb_s3_bucket: "vertica"
    aws_config_path: "/root/ansible/vertica/files/aws_credentials"
    auth_config_path: "/root/ansible/vertica/files/auth_params.conf"
  gather_facts: yes
  tasks:
    - name: Upgrade pip to latest
      pip:
        name: pip
        state: latest
    - name: Install or upgrade required purity-fb Python module
      pip:
        name: purity-fb
        state: latest
    - name: Collect default set of info
      purefb_info:
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"
      register: blade_info
    - name: Show default information
      debug:
        msg: "{{ blade_info['purefb_info']['default'] }}"
    - name: Create new Filesystem to use for PoC
      purefb_fs:
        name: "{{ fb_fs_name }}"
        size: "{{ fb_fs_size }}"
        snapshot: true
        fastremove: true
        nfsv4: false
        state: present
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"
    - name: Create new S3 Account to use for PoC
      purefb_s3acc:
        name: "{{ fb_s3_acct }}"
        state: present
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"
    - name: Create new S3 User to use for PoC and record credentials
      purefb_s3user:
        name: "{{ fb_s3_user }}"
        account: "{{ fb_s3_acct }}"
        state: present
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"
      register: result
    - debug:
        msg: "S3 User: {{ result['s3user_info'] }}"
    - name: Save credentials in AWS Config file
      blockinfile:
        path: "{{ aws_config_path }}"
        backup: yes
        create: yes
        marker: "### {mark} FlashBlade S3 Credestials for Account = {{ fb_s3_acct }}/{{ fb_s3_user }}"
        block: |
          [default]
          aws_access_key_id = {{ result['s3user_info']['fb_s3user']['access_id'] }}
          aws_secret_access_key = {{ result['s3user_info']['fb_s3user']['access_key'] }}
    - name: Save credentials in auth_params file
      blockinfile:
        path: "{{ auth_config_path }}"
        backup: yes
        create: yes
        marker: ''
        block: |
          awsenablehttps = 0
          awsauth = {{ result['s3user_info']['fb_s3user']['access_id'] }}:{{ result['s3user_info']['fb_s3user']['access_key'] }}
          awsendpoint = {{ fb_data }}
    - name: Create new S3 Bucket to use for PoC
      purefb_bucket:
        name: "{{ fb_s3_bucket }}"
        account: "{{ fb_s3_acct }}"
        state: present
        fb_url: "{{ fb_url }}"
        api_token: "{{ fb_api_token }}"