# Install Golang on the hosts
# Example URL: https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz
---
- name: Install Golang on the hosts
  hosts: "{{ hosts_prompt }}"
  vars_prompt:
     ### Host where playbook about to play
   - name: "hosts_prompt"
     prompt: "Enter the Host or Host group need to run with this Playbook"
     private: no
  vars:
    go_ver:  "1.14.4"
    go_os:   "linux"
    go_arch: "amd64"
    go_url:  "https://dl.google.com/go"
    go_path: "/usr/local/go/bin"
  gather_facts: yes
  tasks:
    - name: "Check if Go is already installed"
      stat: 
        path: "{{ go_path }}/go"
      register: go_bin

    - name: "Download and Extract the Golang binaries"
      unarchive:
        src: "{{ go_url }}/go{{ go_ver }}.{{ go_os }}-{{ go_arch }}.tar.gz"
        dest: /usr/local
        remote_src: yes
      when: go_bin.stat.exists == False

    - name: "Check if Go already in /etc/profile.d/custom-path.sh"
      shell: 
        cmd: grep 'bin/go' /etc/profile.d/custom-path.sh
      ignore_errors: yes
      register: go_custom_path

    - name: "Add the Go bin directory to system-wide $PATH"
      blockinfile:
        dest: /etc/profile.d/custom-path.sh
        block: |
          PATH=$PATH:{{ go_path }}:$HOME/go/bin
        marker: "# {mark} ANSIBLE MANAGED BLOCK install Golang"
        mode: '0644'
        create: yes
        backup: yes
      when: go_custom_path.stdout | length == 0

    - name: "Get expected Go workspace"
      shell:
        cmd: go env GOPATH
      register: go_path
    - debug: var=go_path.stdout_lines

    - name: "Create Go workspace directory"
      file:
        path: "{{ go_path.stdout_lines[0] }}"
        state: directory

    - name: "Create Hello World src directory"
      vars:
        hello_path: "{{ go_path.stdout_lines[0] }}/src/hello"
      file:
        path: "{{ hello_path }}"
        state: directory
        recurse: yes

    - name: "Copy Hello World code over"
      vars:
        hello_path: "{{ go_path.stdout_lines[0] }}/src/hello"
      copy:
        src: files/hello.go
        dest: "{{ hello_path }}/hello.go"

    - name: "Build and run Hello World with Go"
      vars:
        hello_path: "{{ go_path.stdout_lines[0] }}/src/hello"
      shell:
        cmd: "cd {{ hello_path }} && go build && ./hello"
      register: hello_out
    - debug: var=hello_out.stdout_lines

...

