# Configure root to have right credentials on target hosts
---
- name: Configure users on the test hosts
  hosts: "{{ hosts_prompt }}"
  gather_facts: yes
  vars_prompt:
     ### Host where playbook about to play
   - name: "hosts_prompt" 
     prompt: "Enter the Host or Host group need to run with this Playbook"
     private: no
  vars:
    username: "root"
    usergroup: "root"
    keyname: "vertica-poc" 
    keypath: "~/.ssh/{{ keyname }}"
  tasks:
    - name: Copy PoC SSH keys to ~/.ssh directory
      copy:
        src: "{{ item }}"
        dest: "~/.ssh/"
        mode: '0600'
        owner: "{{ username }}"
        group: "{{ usergroup }}"
      with_fileglob: "{{ keypath }}*"

    - name: Fix permissions on public key
      file:
        path: "{{ keypath }}.pub"
        mode: '0644'

    - name: Generate authorized_keys from .pub
      copy:
        src: "{{ keypath }}.pub"
        dest: "~/.ssh/authorized_keys"
        mode: '0644'
        owner: "{{ username }}"
        group: "{{ usergroup }}"

    - name: Generate .ssh/config file
      copy:
        content: |
          Host *
            IdentityFile {{ keypath }}
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
        dest: "~/.ssh/config"
        mode: '0600'
        owner: "{{ username }}"
        group: "{{ usergroup }}"

    - name: "Create the .aws directory"
      file:
        path: "/home/{{ username }}/.aws"
        state: directory
        owner: "{{ username }}"
        group: "{{ usergroup }}"
        
    - name: "Copy FlashBlade S3 credentials to ~/.aws directory"
      copy:
        src: "{{ aws_src }}"
        dest: "/home/{{ username }}/.aws/credentials"
        mode: '0600'
        owner: "{{ username }}"
        group: "{{ usergroup }}"

...

