# Install Vertica and configure the dbadmin user
---
- name: Install Vertica and configure the dbadmin user
  hosts: "{{ hosts_prompt }}"
  vars_prompt:
     ### Host where playbook about to play
   - name: "hosts_prompt"
     prompt: "Enter the Host or Host group need to run with this Playbook"
     private: no
  vars:
    auth_file: "files/auth_params.conf"
    vertica_pkg: "vertica-10.0.0-0.x86_64.RHEL6.rpm"
  gather_facts: yes
  tasks:
    - name: Copy the Vertica package to hosts
      copy:
        src: "files/{{ vertica_pkg }}"
        dest: "/tmp/"
        mode: "0644"
      register: out
    - debug: var=out
    - name: Install the Vertica package
      package:
        name: "/tmp/{{ vertica_pkg }}"
        state: latest
      register: out
    - debug: var=out.results
    - name: Gather package facts
      package_facts:
    - name: Vertify that the Vertica package is installed
      debug:
        msg: "{{ ansible_facts.packages['vertica'] | length }} version(s) of Vertica installed"
      when: "'vertica' in ansible_facts.packages"

    - name: Add Vertica custom paths file
      blockinfile:
        dest: "/etc/profile.d/custom-path.sh"
        block: 'PATH=$PATH:/opt/vertica/bin' 
        marker: '# {mark} ANSIBLE MANAGED BLOCK add Vertica binaries' 
        mode: "0644"