# Check that hosts are ready for Vertica
---
- name: Check that hosts are ready for Vertica
  hosts: "{{ hosts_prompt }}"
  vars_prompt:
     ### Host where playbook about to play
   - name: "hosts_prompt"
     prompt: "Enter the Host or Host group need to run with this Playbook"
     private: no
  gather_facts: yes
  tasks:
    - name: Get perl version
      shell:
        cmd: perl --version | grep 'This is perl'
      register: out
    - debug: 
        msg: "{{ out.stdout_lines }}"
    - pause:
        prompt: "Make sure we are using Perl version 5 or later"

    - name: Check socket states for required ports not being used
      shell:
        cmd: ss -atupn | grep -E ':5433|:5434|:5444|:5450|:4803|:4804|:6543' 
      register: out
      ignore_errors: yes
    - debug: 
        msg: "{{ out.stderr_lines }}"
    - pause:
        prompt: "None of the ports should be in use right now"

    - name: Check that Huge Pages set to Always
      shell:
        cmd: cat /sys/kernel/mm/transparent_hugepage/enabled
      register: out
    - debug: 
        msg: "{{ out.stdout_lines }}"
    - pause:
        prompt: "Huge pages should be enabled for RHEL/CentOS 7 and Amazon Linux 2.0"

...

