# Create new Vertica database
---
- name: Create new Vertica database
  hosts: "{{ hg }}[0]"
  vars_prompt:
   - name: "hg"
     prompt: |
       This playbook will install a new Vertica database
       on a set of standby nodes. You will need to enter 
       the name of the Host Group with the hosts for the 
       cluster. The first host in the group will run the 
       install script across other specified hosts.
       
       ]==--> Which host group? 
     private: no
   - name: "node_priv"
     prompt: |
       Next, we need a comma-separated list of host 
       private IP addresses (or DNS names) to use for
       the nodes. Commas between names, no spaces. 
       For example -- 

       vertica-priv-01,vertica-priv-02,vertica-priv-03

       You will be able to add additional nodes later. 
       ]==---> Which private interfaces? 
     private: no
  vars:
    bucket_path: "s3://vertica/prod-01/"
    depot_path: "/home/dbadmin/depot"
    depot_sz: "128G"
    db_shards: "12"
    db_name: "verticadb"
    auth_path: "~/auth_params.conf"
    run_as: "dbadmin"
    run_cmd: >-
      admintools -t create_db -x {{ auth_path }}
      --communal-storage-location={{ bucket_path }}
      --depot-path={{ depot_path }} --depot-size={{ depot_sz }}
      --database={{ db_name }} --shard-count={{ db_shards }}
      --hosts={{ node_priv }}
  gather_facts: yes
  tasks:

    - debug: var=run_cmd

    - pause:
        prompt: |
          The above command will be run on the first host
          in the supplied host group. If everything look good, 
          hit Ctrl-C and then "C" to continue or "A" to abort.

    - name: Run the Vertica Install Script 
      shell:
        cmd: "{{ run_cmd }}"          
      become: yes
      become_user: "{{ run_as }}"
      become_method: su
      register: out
    - debug: var=out

