# Install Vertica Management Console
---
- name: Install Vertica Management Console
  hosts: "{{ hosts_prompt }}"
  vars_prompt:
     ### Host where playbook about to play
   - name: "hosts_prompt"
     prompt: "Enter the Host on which to install the Vertica Management Console (e.g., local)"
     private: no
  vars:
    console_pkg: "vertica-console-10.0.0-0.x86_64.RHEL6.rpm"
  gather_facts: yes
  tasks:
    - name: Copy the Vertica Management Console package to hosts
      copy:
        src: "files/{{ console_pkg }}"
        dest: "/tmp/"
        mode: "0644"
      register: out
    - debug: var=out

    - name: Install the Vertica Management Console package
      package:
        name: "/tmp/{{ console_pkg }}"
        state: latest
      register: out
    - debug: var=out.results
    - name: Gather package facts
      package_facts:
    - name: Vertify that the Vertica Management Console package is installed
      debug:
        msg: "{{ ansible_facts.packages['vertica-console'] | length }} version(s) of Vertica installed"
      when: "'vertica-console' in ansible_facts.packages"

    - name: Start and enable the Vertica Management Console service
      systemd:
        name: vertica-consoled
        state: started
        enabled: yes
    - name: Gather service facts
      service_facts:
    - name: Check vertica-consoled status
      debug:
        msg: "{{ ansible_facts.services['vertica-consoled.service'] }}"
